
wxrpc:
  reflect:
    type: jdk
  providers: http://localhost:8081,http://localhost:8082,http://localhost:8083
  loadbalance: roundrobin


server:
  port: 8080

app:
  id: wxrpc
  namespace: public
  env: dev